<?php

namespace Omnify\Workflow\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class WorkflowInstanceResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'workflow_definition_id' => $this->workflow_definition_id,
            'workflowable_type' => $this->workflowable_type,
            'workflowable_id' => $this->workflowable_id,
            'status' => $this->status,
            'current_step' => $this->current_step,
            'submitted_by' => $this->submitted_by,
            'submitted_at' => $this->submitted_at?->toISOString(),
            'completed_at' => $this->completed_at?->toISOString(),
            'metadata' => $this->metadata,
            'definition_id' => $this->definition_id,
            'definition' => $this->whenLoaded('definition', fn() => new \Omnify\Workflow\Http\Resources\WorkflowDefinitionResource($this->definition)),
            'stepApprovals' => $this->whenLoaded('stepApprovals', fn() => \Omnify\Workflow\Http\Resources\WorkflowStepApprovalResource::collection($this->stepApprovals)),
            'history' => $this->whenLoaded('history', fn() => \Omnify\Workflow\Http\Resources\WorkflowHistoryResource::collection($this->history)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
