<?php

namespace Omnify\Workflow\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class WorkflowDefinitionResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'slug' => $this->slug,
            'console_organization_id' => $this->console_organization_id,
            'name' => $this->name,
            'description' => $this->description,
            'is_active' => $this->is_active,
            'config' => $this->config,
            'steps' => $this->whenLoaded('steps', fn() => \Omnify\Workflow\Http\Resources\WorkflowDefinitionStepResource::collection($this->steps)),
            'instances' => $this->whenLoaded('instances', fn() => \Omnify\Workflow\Http\Resources\WorkflowInstanceResource::collection($this->instances)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
