<?php

namespace Omnify\Workflow\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class WorkflowHistoryResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'workflow_instance_id' => $this->workflow_instance_id,
            'actor_id' => $this->actor_id,
            'action' => $this->action,
            'from_status' => $this->from_status,
            'to_status' => $this->to_status,
            'step_order' => $this->step_order,
            'comment' => $this->comment,
            'metadata' => $this->metadata,
            'created_at' => $this->created_at?->toISOString(),
            'instance_id' => $this->instance_id,
            'instance' => $this->whenLoaded('instance', fn() => new \Omnify\Workflow\Http\Resources\WorkflowInstanceResource($this->instance)),
        ];
    }
}
