<?php

namespace Omnify\Workflow\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class WorkflowStepApprovalResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'workflow_instance_id' => $this->workflow_instance_id,
            'workflow_definition_step_id' => $this->workflow_definition_step_id,
            'step_order' => $this->step_order,
            'approver_id' => $this->approver_id,
            'approver_role' => $this->approver_role,
            'status' => $this->status,
            'comment' => $this->comment,
            'decided_at' => $this->decided_at?->toISOString(),
            'deadline_at' => $this->deadline_at?->toISOString(),
            'notified_at' => $this->notified_at?->toISOString(),
            'instance_id' => $this->instance_id,
            'instance' => $this->whenLoaded('instance', fn() => new \Omnify\Workflow\Http\Resources\WorkflowInstanceResource($this->instance)),
            'definition_step_id' => $this->definition_step_id,
            'definitionStep' => $this->whenLoaded('definitionStep', fn() => new \Omnify\Workflow\Http\Resources\WorkflowDefinitionStepResource($this->definitionStep)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
