<?php

namespace Omnify\Workflow\Models\Base;

/**
 * Base model class for all Omnify-generated models.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
}
