<?php

namespace Omnify\Workflow\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Workflow\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Workflow\Models\Base\Locales\WorkflowDefinitionLocales;

/**
 * WorkflowDefinitionBaseModel
 *
 * @property string $slug
 * @property string|null $console_organization_id
 * @property string $name
 * @property string|null $description
 * @property bool $is_active
 * @property array|null $config
 */
class WorkflowDefinitionBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    /**
     * The table associated with the model.
     */
    protected $table = 'workflow_definitions';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = WorkflowDefinitionLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = WorkflowDefinitionLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'slug',
        'console_organization_id',
        'name',
        'description',
        'is_active',
        'config',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'config' => 'array',
        ];
    }

    /**
     * Get the steps for this model.
     */
    public function steps(): HasMany
    {
        return $this->hasMany(\Omnify\Workflow\Models\WorkflowDefinitionStep::class, 'steps_id');
    }

    /**
     * Get the instances for this model.
     */
    public function instances(): HasMany
    {
        return $this->hasMany(\Omnify\Workflow\Models\WorkflowInstance::class, 'instances_id');
    }
}
