<?php

namespace Omnify\Workflow\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Workflow\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Workflow\Models\Base\Locales\WorkflowDefinitionStepLocales;

/**
 * WorkflowDefinitionStepBaseModel
 *
 * @property string $workflow_definition_id
 * @property int $step_order
 * @property string $name
 * @property string|null $description
 * @property string|null $approver_role
 * @property string $type
 * @property int|null $deadline_hours
 * @property string|null $escalate_to_role
 * @property int $definition_id
 */
class WorkflowDefinitionStepBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    /**
     * The table associated with the model.
     */
    protected $table = 'workflow_definition_steps';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = WorkflowDefinitionStepLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = WorkflowDefinitionStepLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'workflow_definition_id',
        'step_order',
        'name',
        'description',
        'approver_role',
        'type',
        'deadline_hours',
        'escalate_to_role',
        'definition_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'step_order' => 'integer',
            'deadline_hours' => 'integer',
        ];
    }

    /**
     * Get the definition that owns this model.
     */
    public function definition(): BelongsTo
    {
        return $this->belongsTo(\Omnify\Workflow\Models\WorkflowDefinition::class, 'definition_id');
    }
}
