<?php

namespace Omnify\Workflow\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Workflow\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Workflow\Models\Base\Locales\WorkflowStepApprovalLocales;

/**
 * WorkflowStepApprovalBaseModel
 *
 * @property string $workflow_instance_id
 * @property string|null $workflow_definition_step_id
 * @property int $step_order
 * @property string|null $approver_id
 * @property string|null $approver_role
 * @property string $status
 * @property string|null $comment
 * @property mixed|null $decided_at
 * @property mixed|null $deadline_at
 * @property mixed|null $notified_at
 */
class WorkflowStepApprovalBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    /**
     * The table associated with the model.
     */
    protected $table = 'workflow_step_approvals';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = WorkflowStepApprovalLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = WorkflowStepApprovalLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'workflow_instance_id',
        'workflow_definition_step_id',
        'step_order',
        'approver_id',
        'approver_role',
        'status',
        'comment',
        'decided_at',
        'deadline_at',
        'notified_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'step_order' => 'integer',
            'decided_at' => 'datetime',
            'deadline_at' => 'datetime',
            'notified_at' => 'datetime',
        ];
    }

}
