<?php

namespace Omnify\Workflow\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Workflow\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Workflow\Models\Base\Locales\WorkflowHistoryLocales;

/**
 * WorkflowHistoryBaseModel
 *
 * @property string $workflow_instance_id
 * @property string|null $actor_id
 * @property string $action
 * @property string|null $from_status
 * @property string|null $to_status
 * @property int|null $step_order
 * @property string|null $comment
 * @property array|null $metadata
 * @property mixed|null $created_at
 */
class WorkflowHistoryBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    /**
     * The table associated with the model.
     */
    protected $table = 'workflow_histories';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = false;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = WorkflowHistoryLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = WorkflowHistoryLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'workflow_instance_id',
        'actor_id',
        'action',
        'from_status',
        'to_status',
        'step_order',
        'comment',
        'metadata',
        'created_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'step_order' => 'integer',
            'metadata' => 'array',
            'created_at' => 'datetime',
        ];
    }

}
