<?php

namespace Omnify\Workflow\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Workflow\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Workflow\Models\Base\Locales\WorkflowInstanceLocales;

/**
 * WorkflowInstanceBaseModel
 *
 * @property string|null $workflow_definition_id
 * @property string $workflowable_type
 * @property string $workflowable_id
 * @property string $status
 * @property int $current_step
 * @property string|null $submitted_by
 * @property mixed|null $submitted_at
 * @property mixed|null $completed_at
 * @property array|null $metadata
 */
class WorkflowInstanceBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    /**
     * The table associated with the model.
     */
    protected $table = 'workflow_instances';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = WorkflowInstanceLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = WorkflowInstanceLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'workflow_definition_id',
        'workflowable_type',
        'workflowable_id',
        'status',
        'current_step',
        'submitted_by',
        'submitted_at',
        'completed_at',
        'metadata',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'current_step' => 'integer',
            'submitted_at' => 'datetime',
            'completed_at' => 'datetime',
            'metadata' => 'array',
        ];
    }

    /**
     * Get the stepApprovals for this model.
     */
    public function stepApprovals(): HasMany
    {
        return $this->hasMany(\Omnify\Workflow\Models\WorkflowStepApproval::class, 'step_approvals_id');
    }

    /**
     * Get the history for this model.
     */
    public function history(): HasMany
    {
        return $this->hasMany(\Omnify\Workflow\Models\WorkflowHistory::class, 'history_id');
    }
}
