<?php

namespace App\Http\Requests\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Http\FormRequest;
use Omnify\Workflow\Models\Base\Locales\WorkflowStepApprovalLocales;

abstract class WorkflowStepApprovalStoreRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'workflow_instance_id' => ['required', 'string', 'uuid'],
            'workflow_definition_step_id' => ['nullable', 'string', 'uuid'],
            'step_order' => ['required', 'integer'],
            'approver_id' => ['nullable', 'string', 'uuid'],
            'approver_role' => ['nullable', 'string', 'max:100'],
            'status' => ['required', 'string', 'max:20'],
            'comment' => ['nullable', 'string'],
            'decided_at' => ['nullable', 'date'],
            'deadline_at' => ['nullable', 'date'],
            'notified_at' => ['nullable', 'date'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = WorkflowStepApprovalLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'workflow_instance_id',
            'workflow_definition_step_id',
            'step_order',
            'approver_id',
            'approver_role',
            'status',
            'comment',
            'decided_at',
            'deadline_at',
            'notified_at',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
