<?php

namespace App\Http\Requests\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Http\FormRequest;
use Omnify\Workflow\Models\Base\Locales\WorkflowDefinitionStepLocales;

abstract class WorkflowDefinitionStepUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'workflow_definition_id' => ['sometimes', 'string', 'uuid'],
            'step_order' => ['sometimes', 'integer'],
            'name' => ['sometimes', 'string', 'max:200'],
            'description' => ['nullable', 'string'],
            'approver_role' => ['nullable', 'string', 'max:100'],
            'type' => ['sometimes', 'string', 'max:20'],
            'deadline_hours' => ['nullable', 'integer'],
            'escalate_to_role' => ['nullable', 'string', 'max:100'],
            'definition_id' => ['sometimes', 'integer', 'exists:workflow_definitions,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = WorkflowDefinitionStepLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'workflow_definition_id',
            'step_order',
            'name',
            'description',
            'approver_role',
            'type',
            'deadline_hours',
            'escalate_to_role',
            'definition_id',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
