<?php

namespace App\Http\Requests\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Http\FormRequest;
use Omnify\Workflow\Models\Base\Locales\WorkflowInstanceLocales;

abstract class WorkflowInstanceUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'workflow_definition_id' => ['nullable', 'string', 'uuid'],
            'workflowable_type' => ['sometimes', 'string', 'max:200'],
            'workflowable_id' => ['sometimes', 'string', 'max:36'],
            'status' => ['sometimes', 'string', 'max:20'],
            'current_step' => ['sometimes', 'integer'],
            'submitted_by' => ['nullable', 'string', 'uuid'],
            'submitted_at' => ['nullable', 'date'],
            'completed_at' => ['nullable', 'date'],
            'metadata' => ['nullable', 'array'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = WorkflowInstanceLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'workflow_definition_id',
            'workflowable_type',
            'workflowable_id',
            'status',
            'current_step',
            'submitted_by',
            'submitted_at',
            'completed_at',
            'metadata',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
