<?php

namespace Omnify\Workflow\Models\Base\Locales;

/**
 * Localized display names for WorkflowDefinition.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class WorkflowDefinitionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Workflow Definition',
        'vi' => 'Định nghĩa quy trình phê duyệt',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'slug' => [
            'en' => 'Slug',
            'vi' => 'Mã định danh',
        ],
        'console_organization_id' => [
            'en' => 'Organization ID',
            'vi' => 'ID tổ chức',
        ],
        'name' => [
            'en' => 'Name',
            'vi' => 'Tên quy trình',
        ],
        'description' => [
            'en' => 'Description',
            'vi' => 'Mô tả',
        ],
        'is_active' => [
            'en' => 'Active',
            'vi' => 'Đang hoạt động',
        ],
        'config' => [
            'en' => 'Config Override',
            'vi' => 'Cấu hình mở rộng',
        ],
    ];
}
