<?php

namespace Omnify\Workflow\Models\Base\Locales;

/**
 * Localized display names for WorkflowHistory.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class WorkflowHistoryLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Workflow History',
        'vi' => 'Lịch sử quy trình',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'workflow_instance_id' => [
            'en' => 'Workflow Instance',
            'vi' => 'Phiên bản quy trình',
        ],
        'actor_id' => [
            'en' => 'Actor',
            'vi' => 'Người thực hiện',
        ],
        'action' => [
            'en' => 'Action',
            'vi' => 'Hành động',
        ],
        'from_status' => [
            'en' => 'From Status',
            'vi' => 'Trạng thái trước',
        ],
        'to_status' => [
            'en' => 'To Status',
            'vi' => 'Trạng thái sau',
        ],
        'step_order' => [
            'en' => 'Step Order',
            'vi' => 'Bước đang xử lý',
        ],
        'comment' => [
            'en' => 'Comment',
            'vi' => 'Nhận xét / Lý do',
        ],
        'metadata' => [
            'en' => 'Metadata',
            'vi' => 'Dữ liệu bổ sung',
        ],
        'created_at' => [
            'en' => 'Created At',
            'vi' => 'Thời điểm xảy ra',
        ],
    ];
}
