<?php

namespace Omnify\Workflow\Models\Base\Locales;

/**
 * Localized display names for WorkflowStepApproval.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class WorkflowStepApprovalLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Workflow Step Approval',
        'vi' => 'Bản ghi phê duyệt bước',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'workflow_instance_id' => [
            'en' => 'Workflow Instance',
            'vi' => 'Phiên bản quy trình',
        ],
        'workflow_definition_step_id' => [
            'en' => 'Definition Step',
            'vi' => 'Bước định nghĩa',
        ],
        'step_order' => [
            'en' => 'Step Order',
            'vi' => 'Thứ tự bước',
        ],
        'approver_id' => [
            'en' => 'Approver ID',
            'vi' => 'ID người phê duyệt',
        ],
        'approver_role' => [
            'en' => 'Approver Role',
            'vi' => 'Vai trò phê duyệt',
        ],
        'status' => [
            'en' => 'Status',
            'vi' => 'Trạng thái phê duyệt',
        ],
        'comment' => [
            'en' => 'Comment',
            'vi' => 'Nhận xét',
        ],
        'decided_at' => [
            'en' => 'Decided At',
            'vi' => 'Thời điểm quyết định',
        ],
        'deadline_at' => [
            'en' => 'Deadline At',
            'vi' => 'Hạn phê duyệt',
        ],
        'notified_at' => [
            'en' => 'Notified At',
            'vi' => 'Thời điểm đã thông báo',
        ],
    ];
}
