<?php

namespace Omnify\Workflow\Models\Base\Locales;

/**
 * Localized display names for WorkflowInstance.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class WorkflowInstanceLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Workflow Instance',
        'vi' => 'Phiên bản quy trình đang chạy',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'workflow_definition_id' => [
            'en' => 'Workflow Definition',
            'vi' => 'Quy trình phê duyệt',
        ],
        'workflowable_type' => [
            'en' => 'Workflowable Type',
            'vi' => 'Loại model chủ',
        ],
        'workflowable_id' => [
            'en' => 'Workflowable ID',
            'vi' => 'ID model chủ',
        ],
        'status' => [
            'en' => 'Status',
            'vi' => 'Trạng thái',
        ],
        'current_step' => [
            'en' => 'Current Step',
            'vi' => 'Bước hiện tại',
        ],
        'submitted_by' => [
            'en' => 'Submitted By',
            'vi' => 'Người submit',
        ],
        'submitted_at' => [
            'en' => 'Submitted At',
            'vi' => 'Thời điểm submit',
        ],
        'completed_at' => [
            'en' => 'Completed At',
            'vi' => 'Thời điểm hoàn thành',
        ],
        'metadata' => [
            'en' => 'Metadata',
            'vi' => 'Dữ liệu bổ sung',
        ],
    ];
}
