<?php

namespace Omnify\Workflow\Models\Base\Locales;

/**
 * Localized display names for WorkflowDefinitionStep.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class WorkflowDefinitionStepLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Workflow Definition Step',
        'vi' => 'Bước quy trình phê duyệt',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'workflow_definition_id' => [
            'en' => 'Workflow Definition',
            'vi' => 'Quy trình phê duyệt',
        ],
        'step_order' => [
            'en' => 'Step Order',
            'vi' => 'Thứ tự bước',
        ],
        'name' => [
            'en' => 'Step Name',
            'vi' => 'Tên bước',
        ],
        'description' => [
            'en' => 'Description',
            'vi' => 'Mô tả bước',
        ],
        'approver_role' => [
            'en' => 'Approver Role',
            'vi' => 'Vai trò phê duyệt',
        ],
        'approver_user_ids' => [
            'en' => 'Approver User IDs',
            'vi' => 'ID người phê duyệt cụ thể',
        ],
        'type' => [
            'en' => 'Approval Type',
            'vi' => 'Kiểu phê duyệt',
        ],
        'deadline_hours' => [
            'en' => 'Deadline Hours',
            'vi' => 'Hạn phê duyệt (giờ)',
        ],
        'escalate_to_role' => [
            'en' => 'Escalate To Role',
            'vi' => 'Chuyển đến vai trò khi quá hạn',
        ],
    ];
}
