<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('workflow_instances', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('workflow_definition_id')->nullable()->comment('Workflow Definition');
            $table->string('workflowable_type', 200)->comment('Workflowable Type');
            $table->string('workflowable_id', 36)->comment('Workflowable ID');
            $table->string('status', 20)->default('pending')->comment('Status');
            $table->integer('current_step')->default(1)->comment('Current Step');
            $table->uuid('submitted_by')->nullable()->comment('Submitted By');
            $table->timestamp('submitted_at')->nullable()->comment('Submitted At');
            $table->timestamp('completed_at')->nullable()->comment('Completed At');
            $table->json('metadata')->nullable()->comment('Metadata');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['workflowable_type', 'workflowable_id'], 'wf_instances_workflowable_index');
            $table->index('status');
            $table->index('submitted_by');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('workflow_instances');
    }
};
