<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('workflow_histories', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('workflow_instance_id')->comment('Workflow Instance');
            $table->uuid('actor_id')->nullable()->comment('Actor');
            $table->string('action', 50)->comment('Action');
            $table->string('from_status', 20)->nullable()->comment('From Status');
            $table->string('to_status', 20)->nullable()->comment('To Status');
            $table->integer('step_order')->nullable()->comment('Step Order');
            $table->text('comment')->nullable()->comment('Comment');
            $table->json('metadata')->nullable()->comment('Metadata');
            $table->timestamp('created_at')->nullable()->comment('Created At');
            $table->index(['workflow_instance_id', 'created_at'], 'wf_history_instance_time_idx');
            $table->index('actor_id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('workflow_histories');
    }
};
