<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('workflow_step_approvals', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('workflow_instance_id')->comment('Workflow Instance');
            $table->uuid('workflow_definition_step_id')->nullable()->comment('Definition Step');
            $table->integer('step_order')->comment('Step Order');
            $table->uuid('approver_id')->nullable()->comment('Approver ID');
            $table->string('approver_role', 100)->nullable()->comment('Approver Role');
            $table->string('status', 20)->default('pending')->comment('Status');
            $table->text('comment')->nullable()->comment('Comment');
            $table->timestamp('decided_at')->nullable()->comment('Decided At');
            $table->timestamp('deadline_at')->nullable()->comment('Deadline At');
            $table->timestamp('notified_at')->nullable()->comment('Notified At');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['workflow_instance_id', 'step_order'], 'wf_step_approvals_instance_step_idx');
            $table->index('approver_id');
            $table->index(['status', 'deadline_at'], 'wf_step_approvals_escalation_idx');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('workflow_step_approvals');
    }
};
