<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('workflow_definition_steps', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('workflow_definition_id')->comment('Workflow Definition');
            $table->integer('step_order')->default(1)->comment('Step Order');
            $table->string('name', 200)->comment('Step Name');
            $table->text('description')->nullable()->comment('Description');
            $table->string('approver_role', 100)->nullable()->comment('Approver Role');
            $table->string('type', 20)->default('sequential')->comment('Approval Type');
            $table->integer('deadline_hours')->nullable()->comment('Deadline Hours');
            $table->string('escalate_to_role', 100)->nullable()->comment('Escalate To Role');
            $table->uuid('definition_id')->comment('Workflow Definition');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->foreign('definition_id')->references('id')->on('workflow_definitions')->onDelete('restrict')->onUpdate('cascade');
            $table->index('definition_id');
            $table->unique(['workflow_definition_id', 'step_order']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('workflow_definition_steps');
    }
};
