<?php

namespace Omnify\Workflow\Providers;

use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\ServiceProvider;

/**
 * Omnify Service Provider
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * - Loads Omnify migrations from database/migrations/omnify
 * - Registers morph map for polymorphic relationships
 *
 * @generated by omnify
 */
class OmnifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Load Omnify migrations from custom directory
        $this->loadMigrationsFrom(database_path('migrations/omnify'));

        // Register morph map for polymorphic relationships
        Relation::enforceMorphMap([
            'WorkflowDefinition' => \Omnify\Workflow\Models\WorkflowDefinition::class,
            'WorkflowDefinitionStep' => \Omnify\Workflow\Models\WorkflowDefinitionStep::class,
            'WorkflowHistory' => \Omnify\Workflow\Models\WorkflowHistory::class,
            'WorkflowInstance' => \Omnify\Workflow\Models\WorkflowInstance::class,
            'WorkflowStepApproval' => \Omnify\Workflow\Models\WorkflowStepApproval::class,
        ]);
    }
}
